### ISSUE TITLE
Logo not rendered

### ISSUE THREAD

**Issue by zetxek** [ByteInternet/community.hypernode.io#19]
The markup is being displayed as text instead of an image.

<img width="585" alt="image" src="https://user-images.githubusercontent.com/240085/72688099-6cd49300-3b04-11ea-938b-b82dde6a13b1.png">

URL: https://community.hypernode.io/#/
Browser: Firefox 72 on Mac.

**Comment by vdloo** [comment]
whoops, looks like docsify got auto update to a version where it wouldn't display images anymore. fixed now, thanks for reporting!

**Comment by zetxek** [comment]
Nice @vdloo the logo shows now.
The emojis seem to be lost, tho:

![image](https://user-images.githubusercontent.com/240085/72717212-e3f54000-3b73-11ea-8a9f-9c1950ae076a.png)

Would you like me to report a new issue?

**Comment by vdloo** [comment]
oh, good catch. should have been more careful, should be fixed now with https://github.com/ByteInternet/community.hypernode.io/pull/21
